server: 
    servlet:
        context-path : /bayern 
    port: 8804 
spring:
    devtools:
        restart:
          enabled: true 
qhc:
    soap: 
        server: 127
        port:         
    frye: 
        protocal: http
        server: localhost
        port: 8801
        application: frye
        
sap:
  currency:
      addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD024
      param: "[{\"key\": \"KURST\", \"value\":\"M\"},{\"key\": \"LANGU\", \"value\":\"1\"}]"
  customer:
      addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD018
      param: "[{\"key\": \"DATUM\", \"value\":\"20190404\"}]"
  incoterm:
      addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD034
      param: "[{\"key\": \"LANGU\", \"value\":\"1\"}]"
      
   